spring.application.name=jobtracker-application-service
server.port=8082

spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5433/applicationdb}
spring.datasource.username=${DATASOURCE_USERNAME:chigolite}
spring.datasource.password=${DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=false
logging.level.org.flywaydb=DEBUG

app.jwt.secret=${JWT_SECRET:super-secret-key-for-development-only-32chars}